/**
 * Generative UI Renderer
 * Dynamically renders React components from agent responses
 */

import React, { Suspense, useState, useEffect } from 'react';
import { AlertTriangle, Loader2 } from 'lucide-react';
import { 
  getComponent, 
  validateComponentProps, 
  getComponentExample,
  type GenerativeUIComponent 
} from './componentRegistry';

interface GenerativeUIRendererProps {
  /** Component specification from agent */
  componentSpec: GenerativeUIComponent;
  /** Fallback content if rendering fails */
  fallback?: React.ReactNode;
  /** Error handler */
  onError?: (error: Error, componentSpec: GenerativeUIComponent) => void;
  /** Success handler */
  onSuccess?: (componentName: string) => void;
  /** Class name for container */
  className?: string;
}

interface RenderState {
  isLoading: boolean;
  error: string | null;
  hasRendered: boolean;
}

/**
 * Main Generative UI Renderer Component
 */
export const GenerativeUIRenderer: React.FC<GenerativeUIRendererProps> = ({
  componentSpec,
  fallback,
  onError,
  onSuccess,
  className = ''
}) => {
  const [renderState, setRenderState] = useState<RenderState>({
    isLoading: true,
    error: null,
    hasRendered: false
  });

  // Reset state when component spec changes
  useEffect(() => {
    setRenderState({
      isLoading: true,
      error: null,
      hasRendered: false
    });
  }, [componentSpec]);

  /**
   * Render the dynamic component
   */
  const renderDynamicComponent = (): React.ReactNode => {
    try {
      const { componentName, props, fallbackText, metadata } = componentSpec;

      // Get component from registry
      const Component = getComponent(componentName);
      
      if (!Component) {
        throw new Error(`Component '${componentName}' not found in registry`);
      }

      // Validate props
      const validation = validateComponentProps(componentName, props);
      if (!validation.isValid) {
        throw new Error(`Invalid props for ${componentName}: ${validation.errors.join(', ')}`);
      }

      // Sanitize props (remove any potentially harmful props)
      const sanitizedProps = sanitizeProps(props);

      // Set success state
      if (!renderState.hasRendered) {
        setRenderState(prev => ({
          ...prev,
          isLoading: false,
          hasRendered: true
        }));
        
        if (onSuccess) {
          onSuccess(componentName);
        }
      }

      return (
        <div 
          className={`generative-ui-component ${className}`}
          data-component={componentName}
          data-source={metadata?.source}
          data-confidence={metadata?.confidence}
        >
          <Component {...sanitizedProps} />
          {metadata && (
            <div className="generative-ui-metadata text-xs text-gray-500 mt-1">
              Generated by {metadata.source} (confidence: {(metadata.confidence * 100).toFixed(0)}%)
            </div>
          )}
        </div>
      );

    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown rendering error';
      
      setRenderState(prev => ({
        ...prev,
        isLoading: false,
        error: errorMessage
      }));

      if (onError) {
        onError(error instanceof Error ? error : new Error(errorMessage), componentSpec);
      }

      return renderErrorFallback(errorMessage);
    }
  };

  /**
   * Sanitize props to remove potentially harmful content
   */
  const sanitizeProps = (props: Record<string, any>): Record<string, any> => {
    const sanitized = { ...props };

    // Remove dangerous props
    const dangerousProps = [
      'dangerouslySetInnerHTML', 
      'ref', 
      'key',
      'suppressContentEditableWarning',
      'suppressHydrationWarning'
    ];
    dangerousProps.forEach(prop => {
      if (prop in sanitized) {
        delete sanitized[prop];
      }
    });

    // Sanitize function props (only allow specific React event handlers)
    Object.keys(sanitized).forEach(key => {
      if (typeof sanitized[key] === 'function') {
        const allowedEventHandlers = [
          'onClick', 'onDoubleClick', 'onMouseDown', 'onMouseEnter', 'onMouseLeave',
          'onMouseMove', 'onMouseOut', 'onMouseOver', 'onMouseUp',
          'onChange', 'onInput', 'onFocus', 'onBlur', 'onSubmit',
          'onKeyDown', 'onKeyPress', 'onKeyUp',
          'onScroll', 'onWheel', 'onLoad', 'onError'
        ];
        
        if (!allowedEventHandlers.includes(key)) {
          delete sanitized[key];
        }
      }
    });

    // Comprehensive string sanitization (XSS prevention)
    Object.keys(sanitized).forEach(key => {
      if (typeof sanitized[key] === 'string') {
        let value = sanitized[key];
        
        // Remove script tags and javascript: URLs
        value = value.replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, '');
        value = value.replace(/javascript:/gi, '');
        value = value.replace(/data:/gi, '');
        
        // Remove on* event handlers in HTML and dangerous tags
        value = value.replace(/\bon\w+\s*=\s*["'][^"']*["']/gi, '');
        value = value.replace(/<(iframe|object|embed|form)\b[^<]*(?:(?!<\/\1>)<[^<]*)*<\/\1>/gi, '');
        
        sanitized[key] = value;
      }
    });

    return sanitized;
  };

  /**
   * Render error fallback
   */
  const renderErrorFallback = (errorMessage: string): React.ReactNode => {
    const fallbackContent = componentSpec.fallbackText || 'Failed to render component';

    return (
      <div className={`generative-ui-error p-3 bg-red-50 border border-red-200 rounded-lg ${className}`}>
        <div className="flex items-center gap-2 text-red-700 mb-2">
          <AlertTriangle className="w-4 h-4" />
          <span className="text-sm font-medium">Rendering Error</span>
        </div>
        <div className="text-sm text-red-600 mb-2">
          {errorMessage}
        </div>
        <div className="text-sm text-gray-700 bg-white p-2 rounded border">
          {fallbackContent}
        </div>
        <div className="text-xs text-gray-500 mt-2">
          Component: {componentSpec.componentName}
        </div>
      </div>
    );
  };

  /**
   * Render loading state
   */
  const renderLoadingState = (): React.ReactNode => {
    return (
      <div className={`generative-ui-loading flex items-center gap-2 p-3 ${className}`}>
        <Loader2 className="w-4 h-4 animate-spin" />
        <span className="text-sm text-gray-600">
          Rendering {componentSpec.componentName}...
        </span>
      </div>
    );
  };

  // Handle loading state
  if (renderState.isLoading) {
    return (
      <Suspense fallback={renderLoadingState()}>
        {renderDynamicComponent()}
      </Suspense>
    );
  }

  // Handle error state
  if (renderState.error) {
    return fallback || renderErrorFallback(renderState.error);
  }

  // Render the component
  return (
    <Suspense fallback={renderLoadingState()}>
      {renderDynamicComponent()}
    </Suspense>
  );
};

/**
 * Utility hook for using Generative UI in components
 */
export const useGenerativeUI = () => {
  const [renderedComponents, setRenderedComponents] = useState<string[]>([]);
  const [renderErrors, setRenderErrors] = useState<Array<{ component: string; error: string }>>([]);

  const handleRenderSuccess = (componentName: string) => {
    setRenderedComponents(prev => [...prev, componentName]);
  };

  const handleRenderError = (error: Error, componentSpec: GenerativeUIComponent) => {
    setRenderErrors(prev => [...prev, {
      component: componentSpec.componentName,
      error: error.message
    }]);
  };

  const clearStats = () => {
    setRenderedComponents([]);
    setRenderErrors([]);
  };

  return {
    renderedComponents,
    renderErrors,
    handleRenderSuccess,
    handleRenderError,
    clearStats,
    stats: {
      totalRendered: renderedComponents.length,
      totalErrors: renderErrors.length,
      successRate: renderedComponents.length / (renderedComponents.length + renderErrors.length) || 0
    }
  };
};

/**
 * Generative UI Container for multiple components
 */
export const GenerativeUIContainer: React.FC<{
  components: GenerativeUIComponent[];
  className?: string;
  onStatsUpdate?: (stats: any) => void;
}> = ({ components, className = '', onStatsUpdate }) => {
  const { handleRenderSuccess, handleRenderError, stats } = useGenerativeUI();

  // Update stats callback
  React.useEffect(() => {
    if (onStatsUpdate) {
      onStatsUpdate(stats);
    }
  }, [stats, onStatsUpdate]);

  return (
    <div className={`generative-ui-container space-y-4 ${className}`}>
      {components.map((componentSpec, index) => (
        <GenerativeUIRenderer
          key={`${componentSpec.componentName}-${index}`}
          componentSpec={componentSpec}
          onSuccess={handleRenderSuccess}
          onError={handleRenderError}
        />
      ))}
      
      {/* Stats display */}
      {components.length > 1 && (
        <div className="generative-ui-stats text-xs text-gray-500 border-t pt-2">
          Rendered {stats.totalRendered} components
          {stats.totalErrors > 0 && ` (${stats.totalErrors} errors)`}
          {stats.successRate > 0 && ` • ${(stats.successRate * 100).toFixed(0)}% success rate`}
        </div>
      )}
    </div>
  );
};

export default GenerativeUIRenderer;